name: corneto_gemsembler
channels:
  - bioconda
  - conda-forge
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=3.0.0
  - blast=2.16.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.1.31
  - comm=0.2.2
  - curl=8.12.1
  - debugpy=1.8.13
  - decorator=5.2.1
  - entrez-direct=22.4
  - exceptiongroup=1.2.2
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - ipython=9.0.2
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.43
  - libasprintf=0.23.1
  - libcurl=8.12.1
  - libedit=3.1.20250104
  - libev=4.33
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgettextpo=0.23.1
  - libgomp=14.2.0
  - libidn2=2.3.8
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libsodium=1.0.20
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - ncbi-vdb=3.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.4.1
  - packaging=24.2
  - parso=0.8.4
  - perl=5.32.1
  - perl-archive-tar=2.40
  - perl-carp=1.50
  - perl-common-sense=3.75
  - perl-compress-raw-bzip2=2.201
  - perl-compress-raw-zlib=2.202
  - perl-encode=3.21
  - perl-exporter=5.74
  - perl-exporter-tiny=1.002002
  - perl-extutils-makemaker=7.70
  - perl-io-compress=2.201
  - perl-io-zlib=1.14
  - perl-json=4.10
  - perl-json-xs=4.03
  - perl-list-moreutils=0.430
  - perl-list-moreutils-xs=0.430
  - perl-parent=0.243
  - perl-pathtools=3.75
  - perl-scalar-list-utils=1.68
  - perl-storable=3.15
  - perl-types-serialiser=1.01
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.0.1
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.50
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.11.0
  - python-dateutil=2.9.0.post0
  - python_abi=3.11
  - pyzmq=26.3.0
  - readline=8.2
  - rpsbproc=0.5.0
  - setuptools=75.8.2
  - six=1.17.0
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.13.0
  - wcwidth=0.2.13
  - wget=1.21.4
  - wheel=0.45.1
  - xz=5.6.4
  - xz-gpl-tools=5.6.4
  - xz-tools=5.6.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - annotated-types==0.7.0
      - anyio==4.9.0
      - appdirs==1.4.4
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - clarabel==0.11.0
      - cobra==0.29.1
      - contourpy==1.3.1
      - corneto==1.0.0.dev12+cc12e5f
      - cvxpy==1.6.5
      - cvxpy-base==1.6.5
      - cycler==0.12.1
      - depinfo==2.2.0
      - dill==0.3.9
      - diskcache==5.6.3
      - executing==2.2.0
      - fonttools==4.56.0
      - future==1.0.0
      - gemsembler==0.9.13
      - graphviz==0.20.3
      - gurobipy==12.0.2
      - h11==0.14.0
      - h5py==3.13.0
      - highspy==1.10.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - idna==3.10
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - joblib==1.5.1
      - jsonpickle==4.0.5
      - kiwisolver==1.4.8
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - metquest==0.1.34
      - mpmath==1.3.0
      - ncbi-genome-download==0.3.3
      - networkx==3.4.2
      - numpy==2.2.4
      - optlang==1.8.3
      - osqp==1.0.4
      - pandas==2.2.3
      - pillow==11.1.0
      - pyarrow==19.0.1
      - pycparser==2.22
      - pydantic==2.11.1
      - pydantic-core==2.33.0
      - pyparsing==3.2.3
      - pyscipopt==5.5.0
      - python-libsbml==5.20.4
      - pytz==2025.2
      - pyvis==0.3.2
      - pyyaml==6.0.2
      - requests==2.32.3
      - rich==14.0.0
      - ruamel-yaml==0.18.10
      - ruamel-yaml-clib==0.2.12
      - scikit-learn==1.6.1
      - scipy==1.14.0
      - scs==3.2.7.post2
      - seaborn==0.13.2
      - sniffio==1.3.1
      - swiglpk==5.0.12
      - sympy==1.13.3
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - urllib3==2.3.0
